### PR TITLE
Doc validate_host inside Azkaban Class

### PR DESCRIPTION
**Pull request by endersonmenezes**
https://github.com/globocom/azkaban-cli/issues/40

I will start documenting the file, and as we can work together, I will document each function in a commit, so we may not repeat the functions.

### CODE REVIEW

**Comment by aguimaraesduarte** [comment]
Is this PR ready or are you still working on it, @endersonmenezes ?

**Comment by endersonmenezes** [comment]
@aguimaraesduarte I'm working on it in my free time.

**Comment by aguimaraesduarte** [comment]
> @aguimaraesduarte I'm working on it in my free time.

Ok. I put in in WIP. Make sure to remove WIP status once it's ready for review

**Comment by endersonmenezes** [comment]
@aguimaraesduarte I used the site 'https://azkaban.readthedocs.io/en/latest/' to get the doubts that I had about the functions, in the end the biggest work I had was with a function, the others I just standardized the way to document . I don't use azkaban but I learned a lot python by doing this little work. I hope in the end I really collaborated with something!

I found in other parts of the code things that point to PEP violations, such as the lack of a blank line, functions that could be considered static methods, but I still don't understand much about it and I don't know if it has a high performance gain, if it is necessary to do .. There are some questions I have...

PS: Sorry to finish this at the end of the [Globo Event](https://opensource.globo.com/hacktoberfest/)

**Review by aguimaraesduarte — APPROVED** [review]

**Comment by aguimaraesduarte** [comment]
Good job @endersonmenezes ! I'm glad you were able to learn about python by working on the documentation. Doc'ing is super important, and it's nice that you set the standard that we should follow for future improvements in this code-base. PEP8 is great in some aspects, but it's a very old standard, so I consider it fine to break some of its rules (like the 79 char limit for a line. Nowadays it's extremely low and something like 120 is much more acceptable).
Feel free to learn more about static methods and other object-oriented related improvements, and if you want to challenge yourself with updating this codebase to use these features, we'll be happy to look at the PR!

**Pull request merged**
