### PR TITLE
Remove useless tearDown of tests

### PR DESCRIPTION
**Pull request by hermancaldara**

### CODE REVIEW

**Comment by aguimaraesduarte** [comment]
@hermancaldara Due to recent PR merges, I think there are 3 more instances of `tearDown` that need to be removed. Could you update your PR? Thanks!

**Comment by hermancaldara** [comment]
Ok @aguimaraesduarte. I will do it later! ;)

**Comment by hermancaldara** [comment]
Done, @aguimaraesduarte!

**Comment by dmvieira** [comment]
LGTM!

**Pull request merged**
