### PR TITLE
add api methods to read the docs

### PR DESCRIPTION
**Pull request by Perkles**
I've added the ``.. autoclass::`` to all the API methods that could ben called by the user in order to explain the methods used to interact with Azkaban. 

I also took the liberty to chose a different theme for the documentation. ``sphinx.ext.githubpages``

readthedocs

I've decided to display each method of the Azkaban class 'manually' by calling:
````.. autoclass:: azkaban_cli.azkaban.Azkaban.methood````
That way I could put a title in each one of them to make it easy to find it on the sidebar.

This approach creates the needing to add all the new methods, 'manually'.
I could been used:
````
.. autoclass:: azkaban_cli.azkaban.Azkaban
 :members:
````
To load all the methods automatically and avoid the downsizing of the approach described above but I've prioritized documentation readability and navigation.

### CODE REVIEW

**Comment by ggalves** [comment]
Hey, @Perkles ! Thank you for contributing, it looks awesome!

I'm new to sphinx, can i run the docs locally? may you add a command to Makefile to help me and others with this?

And how could I upload this to the original docs?

**Comment by Perkles** [comment]
Hi @ggalves.

## Can i run the docs locally? 

Yes, you can. To run locally first you need to have sphinx installed. Hit ``pip install sphynx`` within your vitualenv and you are ready to start. To build the project run ``make html`` inside the ``docs`` folder, it should generate a ``_build`` folder. 
Open the index.html inside  ``_build`` to access your local doc.  

## May you add a command to Makefile to help me and others with this?

I've never done it before, but I can search if that's possible.

## And how could I upload this to the original docs?

First ReadTheDocs finds if our repo has changed:

>[The primary method that Read the Docs uses to detect changes to your documentation and versions is through the use of webhooks. Webhooks are configured with your repository provider, such as GitHub, Bitbucket or GitLab, and with each commit, merge, or other change to your repository, Read the Docs is notified.](https://docs.readthedocs.io/en/stable/builds.html#how-we-build-documentation)

... then it makes a fresh build of our sphynx doc:

>[The first step of the build process is that we check out your code from the repository you have given us. If the code is already checked out, we update the copy to the branch that you have specified in your project’s configuration](https://docs.readthedocs.io/en/stable/builds.html#understanding-what-s-going-on)

Once ReadTheDocs is already configured to listen to this repo, and it is a thing that i can't reach, the build process may happen simply by updating the repo. I may be wrong. If i am please let me know. 

bye

**Comment by Perkles** [comment]
@ggalves i couldn't find anything useful to add at Makefile. 
Is my approach wrong ?

**Comment by ggalves** [comment]
hey @Perkles 

That's fine. It would be better if this tasks could be easier to do, but your docs looks awesome. I got busy this week so I can't give more attention to it by now, but later I will search for options to improve the process. By now, it's fine :)

I would just ask you to add `sphinx`, `sphinx_rtd_theme` and any other libs required to run `make html` command to a `requirements.txt` file inside docs folder.

Thank you again!

**Comment by ggalves** [comment]
You may also add these instructions you gave me to some README.md inside docs folder

**Comment by aguimaraesduarte** [comment]
@ggalves Good to go?

**Comment by ggalves** [comment]
yes @aguimaraesduarte. Thank you @Perkles

**Pull request merged**
